import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DriveFleet Car Rental Platform",
  description: "Generated by DriveFleet Car Rental Platform",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-screen text-white bg-[#000814] overflow-x-hidden">
        
        {/* --- FULL BODY BACKGROUND GLOWS --- */}
        {/* Main Gradient Background */}
        <div className="fixed inset-0 bg-gradient-to-br from-[#000814] via-[#001d3d] to-[#000814] -z-50" />

        {/* Blue Glow (Top Left) */}
        <div className="fixed -left-40 top-0 h-[500px] w-[500px] rounded-full bg-blue-600/10 blur-[120px] -z-50 pointer-events-none" />

        {/* Cyan Glow (Top Right) */}
        <div className="fixed -right-20 top-20 h-[500px] w-[500px] rounded-full bg-cyan-400/10 blur-[120px] -z-50 pointer-events-none" />

        {/* Extra Glow (Middle/Bottom) */}
        <div className="fixed left-1/3 top-1/2 h-[400px] w-[400px] rounded-full bg-indigo-500/10 blur-[120px] -z-50 pointer-events-none" />
        {/* --------------------------------- */}

        {/* আপনার ওয়েবসাইটের বাকি সব পেজ এখানে রেন্ডার হবে */}
        <main className="relative z-10">
          <Navbar />
          {children}
          <Footer />
        </main>

      </body>
    </html>
  );
}
